//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTrainer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTrainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x0][0x0],1 [0x2][0x10],2 [0x0][0x4],3 [0x2][0x11],4 [0x2][0x12],5 [0x2][0x13],6 [0x2][0x14],7 [0x2][0x15],8 [0x0][0x8],9 [0x0][0xc],10 [0x5][0x80],11 [0x5][0x82],12 [0x3][0x8e],13 [0x3][0x8f],14 [0x7][0x68],15 [0x3][0x90],16 [0x3][0x91],17 [0x3][0x92],18 [0x5][0x84],19 [0x7][0x6c],20 [0x19][0x95],21 [0x1a][0x95],22 [0x1b][0x95],23 [0x1c][0x95],24 [0x7][0x70],25 [0x7][0x74],26 [0x1d][0x95],27 [0x1e][0x95],28 [0x1f][0x95],29 [0x5][0x86],30 [0x3][0x93],31 [0x5][0x88],32 [0x3][0x94],33 [0x6][0x78],34  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [BYTE(0x2)][0x10],2 [STRING(0x0)][0x4],3 [BYTE(0x2)][0x11],4 [BYTE(0x2)][0x12],5 [BYTE(0x2)][0x13],6 [BYTE(0x2)][0x14],7 [BYTE(0x2)][0x15],8 [STRING(0x0)][0x8],9 [STRING(0x0)][0xc],10 [USHORT(0x5)][0x80],11 [USHORT(0x5)][0x82],12 [UBYTE(0x3)][0x8e],13 [UBYTE(0x3)][0x8f],14 [UINT(0x7)][0x68],15 [UBYTE(0x3)][0x90],16 [UBYTE(0x3)][0x91],17 [UBYTE(0x3)][0x92],18 [USHORT(0x5)][0x84],19 [UINT(0x7)][0x6c],20 [BBOOL(0x19)][0x95],21 [BBOOL(0x1a)][0x95],22 [BBOOL(0x1b)][0x95],23 [BBOOL(0x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ItemG {
            get {
                return ResourceManager.GetString("ItemG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x0][0x0],1 [0x2][0x10],2 [0x0][0x4],3 [0x2][0x11],4 [0x2][0x12],5 [0x2][0x13],6 [0x2][0x14],7 [0x2][0x15],8 [0x0][0x8],9 [0x0][0xc],10 [0x5][0x80],11 [0x5][0x82],12 [0x3][0x8e],13 [0x3][0x8f],14 [0x7][0x68],15 [0x3][0x90],16 [0x3][0x91],17 [0x3][0x92],18 [0x5][0x84],19 [0x7][0x6c],20 [0x19][0x95],21 [0x1a][0x95],22 [0x1b][0x95],23 [0x1c][0x95],24 [0x7][0x70],25 [0x7][0x74],26 [0x1d][0x95],27 [0x1e][0x95],28 [0x1f][0x95],29 [0x5][0x86],30 [0x3][0x93],31 [0x5][0x88],32 [0x3][0x94],33 [0x6][0x78],34  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string itemJP {
            get {
                return ResourceManager.GetString("itemJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x0][0x0],1 [0x0][0x4],2 [0x3][0x2c],3 [0x5][0x1c],4 [0x5][0x1e],5 [0x5][0x20],6 [0x5][0x22],7 [0x3][0x2d],8 [0x3][0x2e],9 [0x3][0x2f],10 [0x5][0x24],11 [0x19][0x37],12 [0x3][0x30],13 [0x1a][0x37],14 [0x3][0x31],15 [0x1b][0x37],16 [0x1c][0x37],17 [0x1d][0x37],18 [0x1e][0x37],19 [0x5][0x26],20 [0x6][0xc],21 [0x6][0x10],22 [0x7][0x8],23 [0x5][0x28],24 [0x6][0x14],25 [0x6][0x18],26 [0x5][0x2a],27 [0x2][0x36],28 [0x1f][0x37],29 [0x3][0x32],30 [0x3][0x33],31 [0x3][0x34],32 [0x3][0x35],33 [0x20][0x37]
        ///1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string territorytype_exh {
            get {
                return ResourceManager.GetString("territorytype_exh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x6][0x18],1 [0x0][0x0],2 [0x0][0x4],3 [0x0][0x8],4 [0x0][0xc],5 [0x0][0x10],6 [0x0][0x14]
        ///0,0,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///1,60201,&quot;Clear Skies&quot;,&quot;clear&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///2,60202,&quot;Fair Skies&quot;,&quot;fair&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///3,60203,&quot;Clouds&quot;,&quot;overcast&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///4,60204,&quot;Fog&quot;,&quot;foggy&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///5,60205,&quot;Wind&quot;,&quot;windy&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///6,60206,&quot;Gales&quot;,&quot;gusty&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///7,60207,&quot;Rain&quot;,&quot;rainy&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///8,60208,&quot;Showers&quot;,&quot;showery&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///9,60209,&quot;Thunder&quot;,&quot;thundery&quot;,&quot;&q....
        /// </summary>
        public static string weather_0_exh_en {
            get {
                return ResourceManager.GetString("weather_0_exh_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x6][0x0],1 [0x3][0x20],2 [0x6][0x4],3 [0x3][0x21],4 [0x6][0x8],5 [0x3][0x22],6 [0x6][0xc],7 [0x3][0x23],8 [0x6][0x10],9 [0x3][0x24],10 [0x6][0x14],11 [0x3][0x25],12 [0x6][0x18],13 [0x3][0x26],14 [0x6][0x1c],15 [0x3][0x27]
        ///0,2,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///1,7,5,7,15,4,10,3,10,2,15,1,30,2,15,0,0
        ///2,7,5,7,15,4,10,3,10,2,15,1,30,2,15,0,0
        ///3,9,5,7,15,4,10,3,10,2,15,1,30,2,15,0,0
        ///4,9,5,7,15,4,10,3,10,2,15,1,30,2,15,0,0
        ///5,4,5,10,5,9,15,4,5,3,10,2,30,1,30,0,0
        ///6,4,5,8,5,7,15,4,5,3,10,2,30,1,30,0,0
        ///7,1,40, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string weatherrate_exh {
            get {
                return ResourceManager.GetString("weatherrate_exh", resourceCulture);
            }
        }
    }
}
