//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTrainer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTrainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0]
        ///3,&quot;Idle&quot;
        ///4,&quot;Idle 2&quot;
        ///5,&quot;Idle 3&quot;
        ///6,&quot;Idle 4&quot;
        ///7,&quot;Turning Left&quot;
        ///8,&quot;Turning Right&quot;
        ///13,&quot;Walking&quot;
        ///14,&quot;Walking Left&quot;
        ///15,&quot;Walking Right&quot;
        ///16,&quot;Walking Back&quot;
        ///22,&quot;Run&quot;
        ///23,&quot;Run Left&quot;
        ///24,&quot;Run Right&quot;
        ///30,&quot;Sprint&quot;
        ///31,&quot;Jump Start&quot;
        ///32,&quot;Jump Fall&quot;
        ///33,&quot;Jump Landing&quot;
        ///34,&quot;Battle Idle&quot;
        ///37&quot;Knee Suffering&quot;
        ///41,&quot;Battle Walk&quot;
        ///50,&quot;Battle Run&quot;
        ///58,&quot;Battle Sprint&quot;
        ///59,&quot;Battle Jump&quot;
        ///60,&quot;Battle Fall&quot;
        ///61,&quot;Battle Land&quot;
        ///62,&quot;Damaged&quot;
        ///66,&quot;Dying&quot;
        ///68,&quot;Flinch with wince&quot;
        ///69,&quot;Flinch (faster)&quot;
        ///71,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string actiontimeline {
            get {
                return ResourceManager.GetString("actiontimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x0][0x0],1 [0x2][0x10],2 [0x0][0x4],3 [0x2][0x11],4 [0x2][0x12],5 [0x2][0x13],6 [0x2][0x14],7 [0x2][0x15],8 [0x0][0x8],9 [0x0][0xc],10 [0x5][0x80],11 [0x5][0x82],12 [0x3][0x8e],13 [0x3][0x8f],14 [0x7][0x68],15 [0x3][0x90],16 [0x3][0x91],17 [0x3][0x92],18 [0x5][0x84],19 [0x7][0x6c],20 [0x19][0x95],21 [0x1a][0x95],22 [0x1b][0x95],23 [0x1c][0x95],24 [0x7][0x70],25 [0x7][0x74],26 [0x1d][0x95],27 [0x1e][0x95],28 [0x1f][0x95],29 [0x5][0x86],30 [0x3][0x93],31 [0x5][0x88],32 [0x3][0x94],33 [0x6][0x78],34  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [BYTE(0x2)][0x10],2 [STRING(0x0)][0x4],3 [BYTE(0x2)][0x11],4 [BYTE(0x2)][0x12],5 [BYTE(0x2)][0x13],6 [BYTE(0x2)][0x14],7 [BYTE(0x2)][0x15],8 [STRING(0x0)][0x8],9 [STRING(0x0)][0xc],10 [USHORT(0x5)][0x80],11 [USHORT(0x5)][0x82],12 [UBYTE(0x3)][0x8e],13 [UBYTE(0x3)][0x8f],14 [UINT(0x7)][0x68],15 [UBYTE(0x3)][0x90],16 [UBYTE(0x3)][0x91],17 [UBYTE(0x3)][0x92],18 [USHORT(0x5)][0x84],19 [UINT(0x7)][0x6c],20 [BBOOL(0x19)][0x95],21 [BBOOL(0x1a)][0x95],22 [BBOOL(0x1b)][0x95],23 [BBOOL(0x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string item_0_exh_fr {
            get {
                return ResourceManager.GetString("item_0_exh_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [BYTE(0x2)][0x10],2 [STRING(0x0)][0x4],3 [BYTE(0x2)][0x11],4 [BYTE(0x2)][0x12],5 [BYTE(0x2)][0x13],6 [BYTE(0x2)][0x14],7 [BYTE(0x2)][0x15],8 [STRING(0x0)][0x8],9 [STRING(0x0)][0xc],10 [USHORT(0x5)][0x80],11 [USHORT(0x5)][0x82],12 [UBYTE(0x3)][0x8e],13 [UBYTE(0x3)][0x8f],14 [UINT(0x7)][0x68],15 [UBYTE(0x3)][0x90],16 [UBYTE(0x3)][0x91],17 [UBYTE(0x3)][0x92],18 [USHORT(0x5)][0x84],19 [UINT(0x7)][0x6c],20 [BBOOL(0x19)][0x95],21 [BBOOL(0x1a)][0x95],22 [BBOOL(0x1b)][0x95],23 [BBOOL(0x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ItemG {
            get {
                return ResourceManager.GetString("ItemG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x0][0x0],1 [0x2][0x10],2 [0x0][0x4],3 [0x2][0x11],4 [0x2][0x12],5 [0x2][0x13],6 [0x2][0x14],7 [0x2][0x15],8 [0x0][0x8],9 [0x0][0xc],10 [0x5][0x80],11 [0x5][0x82],12 [0x3][0x8e],13 [0x3][0x8f],14 [0x7][0x68],15 [0x3][0x90],16 [0x3][0x91],17 [0x3][0x92],18 [0x5][0x84],19 [0x7][0x6c],20 [0x19][0x95],21 [0x1a][0x95],22 [0x1b][0x95],23 [0x1c][0x95],24 [0x7][0x70],25 [0x7][0x74],26 [0x1d][0x95],27 [0x1e][0x95],28 [0x1f][0x95],29 [0x5][0x86],30 [0x3][0x93],31 [0x5][0x88],32 [0x3][0x94],33 [0x6][0x78],34  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string itemJP {
            get {
                return ResourceManager.GetString("itemJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [INT(0x6)][0x8],3 [INT(0x6)][0x10],4 [INT(0x6)][0x18],5 [INT(0x6)][0x20],6 [INT(0x6)][0xc],7 [INT(0x6)][0x14],8 [INT(0x6)][0x1c],9 [INT(0x6)][0x24]
        ///0,&quot;Aucun&quot;,&quot;Aucun&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;Hyur&quot;,&quot;Hyure&quot;,2983,3520,3296,3750,2984,3521,3297,3751
        ///2,&quot;Élézen&quot;,&quot;Élézenne&quot;,2985,3522,3298,3752,2986,3523,3299,3753
        ///3,&quot;Lalafell&quot;,&quot;Lalafelle&quot;,2987,3524,3300,3754,2988,3525,3301,3755
        ///4,&quot;Miqo&apos;te&quot;,&quot;Miqo&apos;te&quot;,2989,3526,3302,3756,2990,3527,3303,3757
        ///5,&quot;Roegadyn&quot;,&quot;Roegadyne&quot;,299 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string race_exh_fr {
            get {
                return ResourceManager.GetString("race_exh_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [INT(0x6)][0x8],3 [INT(0x6)][0x10],4 [INT(0x6)][0x18],5 [INT(0x6)][0x20],6 [INT(0x6)][0xc],7 [INT(0x6)][0x14],8 [INT(0x6)][0x1c],9 [INT(0x6)][0x24]
        ///0,&quot;Keiner&quot;,&quot;Keiner&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;Hyuran&quot;,&quot;Hyuran&quot;,2983,3520,3296,3750,2984,3521,3297,3751
        ///2,&quot;Elezen&quot;,&quot;Elezen&quot;,2985,3522,3298,3752,2986,3523,3299,3753
        ///3,&quot;Lalafell&quot;,&quot;Lalafell&quot;,2987,3524,3300,3754,2988,3525,3301,3755
        ///4,&quot;Miqo&apos;te&quot;,&quot;Miqo&apos;te&quot;,2989,3526,3302,3756,2990,3527,3303,3757
        ///5,&quot;Roegadyn&quot;,&quot;Roegadyn&quot;,29 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string raceDE {
            get {
                return ResourceManager.GetString("raceDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [INT(0x6)][0x8],3 [INT(0x6)][0x10],4 [INT(0x6)][0x18],5 [INT(0x6)][0x20],6 [INT(0x6)][0xc],7 [INT(0x6)][0x14],8 [INT(0x6)][0x1c],9 [INT(0x6)][0x24]
        ///0,&quot;None&quot;,&quot;None&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;Hyur&quot;,&quot;Hyur&quot;,2983,3520,3296,3750,2984,3521,3297,3751
        ///2,&quot;Elezen&quot;,&quot;Elezen&quot;,2985,3522,3298,3752,2986,3523,3299,3753
        ///3,&quot;Lalafell&quot;,&quot;Lalafell&quot;,2987,3524,3300,3754,2988,3525,3301,3755
        ///4,&quot;Miqo&apos;te&quot;,&quot;Miqo&apos;te&quot;,2989,3526,3302,3756,2990,3527,3303,3757
        ///5,&quot;Roegadyn&quot;,&quot;Roegadyn&quot;,2991,3528, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string raceEN {
            get {
                return ResourceManager.GetString("raceEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [INT(0x6)][0x8],3 [INT(0x6)][0x10],4 [INT(0x6)][0x18],5 [INT(0x6)][0x20],6 [INT(0x6)][0xc],7 [INT(0x6)][0x14],8 [INT(0x6)][0x1c],9 [INT(0x6)][0x24]
        ///0,&quot;なし&quot;,&quot;なし&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;ヒューラン&quot;,&quot;ヒューラン&quot;,2983,3520,3296,3750,2984,3521,3297,3751
        ///2,&quot;エレゼン&quot;,&quot;エレゼン&quot;,2985,3522,3298,3752,2986,3523,3299,3753
        ///3,&quot;ララフェル&quot;,&quot;ララフェル&quot;,2987,3524,3300,3754,2988,3525,3301,3755
        ///4,&quot;ミコッテ&quot;,&quot;ミコッテ&quot;,2989,3526,3302,3756,2990,3527,3303,3757
        ///5,&quot;ルガディン&quot;,&quot;ルガディン&quot;,2991,3528,3304,3758,2992,3529,3305 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string raceJP {
            get {
                return ResourceManager.GetString("raceJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [UINT(0x7)][0x4],1 [UBYTE(0x3)][0x8],2 [STRING(0x0)][0x0],3 [BBOOL(0x19)][0x9],4 [BBOOL(0x1a)][0x9]
        ///0,0,2,&quot;Keiner&quot;,false,true
        ///1,14999504,2,&quot;Schneeweiß&quot;,false,true
        ///2,11315362,2,&quot;Aschgrau&quot;,false,true
        ///3,9013124,2,&quot;Goobbuegrau&quot;,false,true
        ///4,6645093,2,&quot;Schiefergrau&quot;,false,true
        ///5,4736834,2,&quot;Anthrazit&quot;,false,true
        ///6,2828579,2,&quot;Rußschwarz&quot;,false,true
        ///7,15114134,4,&quot;Rosarot&quot;,false,true
        ///8,8612201,4,&quot;Altrosa&quot;,false,true
        ///9,5969705,4,&quot;Rolanbeerenrot&quot;,false,true
        ///10,7871002,4,&quot;Dalamudrot&quot;,false,true
        ///11,6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stain_exh_de {
            get {
                return ResourceManager.GetString("stain_exh_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [UINT(0x7)][0x4],1 [UBYTE(0x3)][0x8],2 [STRING(0x0)][0x0],3 [BBOOL(0x19)][0x9],4 [BBOOL(0x1a)][0x9]
        ///0,0,2,&quot;None&quot;,false,true
        ///1,14999504,2,&quot;Snow White&quot;,false,true
        ///2,11315362,2,&quot;Ash Grey&quot;,false,true
        ///3,9013124,2,&quot;Goobbue Grey&quot;,false,true
        ///4,6645093,2,&quot;Slate Grey&quot;,false,true
        ///5,4736834,2,&quot;Charcoal Grey&quot;,false,true
        ///6,2828579,2,&quot;Soot Black&quot;,false,true
        ///7,15114134,4,&quot;Rose Pink&quot;,false,true
        ///8,8612201,4,&quot;Lilac Purple&quot;,false,true
        ///9,5969705,4,&quot;Rolanberry Red&quot;,false,true
        ///10,7871002,4,&quot;Dalamud Red&quot;,false,t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stain_exh_en {
            get {
                return ResourceManager.GetString("stain_exh_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [UINT(0x7)][0x4],1 [UBYTE(0x3)][0x8],2 [STRING(0x0)][0x0],3 [BBOOL(0x19)][0x9],4 [BBOOL(0x1a)][0x9]
        ///0,0,2,&quot;Aucun&quot;,false,true
        ///1,14999504,2,&quot;blanc neige&quot;,false,true
        ///2,11315362,2,&quot;gris cendre&quot;,false,true
        ///3,9013124,2,&quot;gris goobbue&quot;,false,true
        ///4,6645093,2,&quot;gris ardoise&quot;,false,true
        ///5,4736834,2,&quot;gris charbon&quot;,false,true
        ///6,2828579,2,&quot;noir suie&quot;,false,true
        ///7,15114134,4,&quot;rose floral&quot;,false,true
        ///8,8612201,4,&quot;lilas&quot;,false,true
        ///9,5969705,4,&quot;rouge rolanbaie&quot;,false,true
        ///10,7871002,4,&quot;rouge Dalamud&quot;,fals [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stain_exh_fr {
            get {
                return ResourceManager.GetString("stain_exh_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [UINT(0x7)][0x4],1 [UBYTE(0x3)][0x8],2 [STRING(0x0)][0x0],3 [BBOOL(0x19)][0x9],4 [BBOOL(0x1a)][0x9]
        ///0,0,2,&quot;なし&quot;,false,true
        ///1,14999504,2,&quot;スノウホワイト&quot;,false,true
        ///2,11315362,2,&quot;アッシュグレイ&quot;,false,true
        ///3,9013124,2,&quot;グゥーブーグレイ&quot;,false,true
        ///4,6645093,2,&quot;スレートグレイ&quot;,false,true
        ///5,4736834,2,&quot;チャコールグレイ&quot;,false,true
        ///6,2828579,2,&quot;スートブラック&quot;,false,true
        ///7,15114134,4,&quot;ローズピンク&quot;,false,true
        ///8,8612201,4,&quot;ライラックパープル&quot;,false,true
        ///9,5969705,4,&quot;ロランベリーレッド&quot;,false,true
        ///10,7871002,4,&quot;ダラガブレッド&quot;,false,true
        ///11,6431239,4,&quot;ラストレッド&quot;,false,tru [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stain_exh_ja {
            get {
                return ResourceManager.GetString("stain_exh_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x0][0x0],1 [0x0][0x4],2 [0x3][0x2c],3 [0x5][0x1c],4 [0x5][0x1e],5 [0x5][0x20],6 [0x5][0x22],7 [0x3][0x2d],8 [0x3][0x2e],9 [0x3][0x2f],10 [0x5][0x24],11 [0x19][0x37],12 [0x3][0x30],13 [0x1a][0x37],14 [0x3][0x31],15 [0x1b][0x37],16 [0x1c][0x37],17 [0x1d][0x37],18 [0x1e][0x37],19 [0x5][0x26],20 [0x6][0xc],21 [0x6][0x10],22 [0x7][0x8],23 [0x5][0x28],24 [0x6][0x14],25 [0x6][0x18],26 [0x5][0x2a],27 [0x2][0x36],28 [0x1f][0x37],29 [0x3][0x32],30 [0x3][0x33],31 [0x3][0x34],32 [0x3][0x35],33 [0x20][0x37]
        ///1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string territorytype_exh {
            get {
                return ResourceManager.GetString("territorytype_exh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [BYTE(0x2)][0x8],3 [BYTE(0x2)][0x9],4 [BYTE(0x2)][0xa],5 [BYTE(0x2)][0xb],6 [BYTE(0x2)][0xc],7 [BYTE(0x2)][0xd],8 [BYTE(0x2)][0xe],9 [BYTE(0x2)][0xf]
        ///0,&quot;Keiner&quot;,&quot;Keiner&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;Wiesländer&quot;,&quot;Wiesländer&quot;,0,0,2,0,-1,3,-1,0
        ///2,&quot;Hochländer&quot;,&quot;Hochländer&quot;,0,0,3,2,0,-2,0,0
        ///3,&quot;Erlschatten&quot;,&quot;Erlschatten&quot;,0,0,0,-1,3,2,-1,0
        ///4,&quot;Dunkelalb&quot;,&quot;Dunkelalb&quot;,0,0,0,-1,0,3,1,0
        ///5,&quot;Halmling&quot;,&quot;Halmling&quot;,0,0,-1,-1,3,2,0,0
        ///6,&quot;Sandling&quot;,&quot;Sandling&quot;,0,0,-1,-2,1,2,3,0
        ///7, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tribe_exh_de {
            get {
                return ResourceManager.GetString("tribe_exh_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [BYTE(0x2)][0x8],3 [BYTE(0x2)][0x9],4 [BYTE(0x2)][0xa],5 [BYTE(0x2)][0xb],6 [BYTE(0x2)][0xc],7 [BYTE(0x2)][0xd],8 [BYTE(0x2)][0xe],9 [BYTE(0x2)][0xf]
        ///0,&quot;None&quot;,&quot;None&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;Midlander&quot;,&quot;Midlander&quot;,0,0,2,0,-1,3,-1,0
        ///2,&quot;Highlander&quot;,&quot;Highlander&quot;,0,0,3,2,0,-2,0,0
        ///3,&quot;Wildwood&quot;,&quot;Wildwood&quot;,0,0,0,-1,3,2,-1,0
        ///4,&quot;Duskwight&quot;,&quot;Duskwight&quot;,0,0,0,-1,0,3,1,0
        ///5,&quot;Plainsfolk&quot;,&quot;Plainsfolk&quot;,0,0,-1,-1,3,2,0,0
        ///6,&quot;Dunesfolk&quot;,&quot;Dunesfolk&quot;,0,0,-1,-2,1,2,3,0
        ///7,&quot;Seeke [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tribe_exh_en {
            get {
                return ResourceManager.GetString("tribe_exh_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [BYTE(0x2)][0x8],3 [BYTE(0x2)][0x9],4 [BYTE(0x2)][0xa],5 [BYTE(0x2)][0xb],6 [BYTE(0x2)][0xc],7 [BYTE(0x2)][0xd],8 [BYTE(0x2)][0xe],9 [BYTE(0x2)][0xf]
        ///0,&quot;Aucun&quot;,&quot;Aucun&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;Hyurois&quot;,&quot;Hyuroise&quot;,0,0,2,0,-1,3,-1,0
        ///2,&quot;Hyurgoth&quot;,&quot;Hyurgothe&quot;,0,0,3,2,0,-2,0,0
        ///3,&quot;Sylvestre&quot;,&quot;Sylvestre&quot;,0,0,0,-1,3,2,-1,0
        ///4,&quot;Crépusculaire&quot;,&quot;Crépusculaire&quot;,0,0,0,-1,0,3,1,0
        ///5,&quot;Peuple des Plaines&quot;,&quot;Peuple des Plaines&quot;,0,0,-1,-1,3,2,0,0
        ///6,&quot;Peuple des Dunes&quot;,&quot;Peuple de [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tribe_exh_fr {
            get {
                return ResourceManager.GetString("tribe_exh_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [BYTE(0x2)][0x8],3 [BYTE(0x2)][0x9],4 [BYTE(0x2)][0xa],5 [BYTE(0x2)][0xb],6 [BYTE(0x2)][0xc],7 [BYTE(0x2)][0xd],8 [BYTE(0x2)][0xe],9 [BYTE(0x2)][0xf]
        ///0,&quot;なし&quot;,&quot;なし&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;ミッドランダー &quot;,&quot;ミッドランダー &quot;,0,0,2,0,-1,3,-1,0
        ///2,&quot;ハイランダー&quot;,&quot;ハイランダー&quot;,0,0,3,2,0,-2,0,0
        ///3,&quot;フォレスター&quot;,&quot;フォレスター&quot;,0,0,0,-1,3,2,-1,0
        ///4,&quot;シェーダー&quot;,&quot;シェーダー&quot;,0,0,0,-1,0,3,1,0
        ///5,&quot;プレーンフォーク&quot;,&quot;プレーンフォーク&quot;,0,0,-1,-1,3,2,0,0
        ///6,&quot;デューンフォーク&quot;,&quot;デューンフォーク&quot;,0,0,-1,-2,1,2,3,0
        ///7,&quot;サンシーカー&quot;,&quot;サンシーカー&quot;,0,0,2,0,3,-1,-1,0
        ///8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tribe_exh_ja {
            get {
                return ResourceManager.GetString("tribe_exh_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x6][0x18],1 [0x0][0x0],2 [0x0][0x4],3 [0x0][0x8],4 [0x0][0xc],5 [0x0][0x10],6 [0x0][0x14]
        ///0,0,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///1,60201,&quot;Clear Skies&quot;,&quot;clear&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///2,60202,&quot;Fair Skies&quot;,&quot;fair&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///3,60203,&quot;Clouds&quot;,&quot;overcast&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///4,60204,&quot;Fog&quot;,&quot;foggy&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///5,60205,&quot;Wind&quot;,&quot;windy&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///6,60206,&quot;Gales&quot;,&quot;gusty&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///7,60207,&quot;Rain&quot;,&quot;rainy&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///8,60208,&quot;Showers&quot;,&quot;showery&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///9,60209,&quot;Thunder&quot;,&quot;thundery&quot;,&quot;&q....
        /// </summary>
        public static string weather_0_exh_en {
            get {
                return ResourceManager.GetString("weather_0_exh_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [INT(0x6)][0x18],1 [STRING(0x0)][0x0],2 [STRING(0x0)][0x4],3 [STRING(0x0)][0x8],4 [STRING(0x0)][0xc],5 [STRING(0x0)][0x10],6 [STRING(0x0)][0x14]
        ///0,0,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///1,60201,&quot;Dégagé&quot;,&quot;radieux&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///2,60202,&quot;Clair&quot;,&quot;ensoleillé&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///3,60203,&quot;Couvert&quot;,&quot;couvert&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///4,60204,&quot;Brouillard&quot;,&quot;brumeux&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///5,60205,&quot;Vent&quot;,&quot;venteux&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///6,60206,&quot;Vents violents&quot;,&quot;très venteux&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///7,60207,&quot;Pluie&quot;,&quot;pluvieux&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///8,60208,&quot;Pluie torrentielle&quot;,&quot;très pl [rest of stri....
        /// </summary>
        public static string weather_0_exh_fr {
            get {
                return ResourceManager.GetString("weather_0_exh_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [INT(0x6)][0x18],1 [STRING(0x0)][0x0],2 [STRING(0x0)][0x4],3 [STRING(0x0)][0x8],4 [STRING(0x0)][0xc],5 [STRING(0x0)][0x10],6 [STRING(0x0)][0x14]
        ///0,0,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///1,60201,&quot;Klar&quot;,&quot;klar&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///2,60202,&quot;Heiter&quot;,&quot;heiter&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///3,60203,&quot;Wolkig&quot;,&quot;wolkig&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///4,60204,&quot;Neblig&quot;,&quot;nebelig&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///5,60205,&quot;Windig&quot;,&quot;windig&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///6,60206,&quot;Stürmisch&quot;,&quot;stürmisch&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///7,60207,&quot;Regnerisch&quot;,&quot;regnerisch&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///8,60208,&quot;Wolkenbruch&quot;,&quot;wolkenbruchartig&quot;,&quot;&quot;,&quot;....
        /// </summary>
        public static string weatherDE {
            get {
                return ResourceManager.GetString("weatherDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [INT(0x6)][0x18],1 [STRING(0x0)][0x0],2 [STRING(0x0)][0x4],3 [STRING(0x0)][0x8],4 [STRING(0x0)][0xc],5 [STRING(0x0)][0x10],6 [STRING(0x0)][0x14]
        ///0,0,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///1,60201,&quot;快晴&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///2,60202,&quot;晴れ&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///3,60203,&quot;曇り&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///4,60204,&quot;霧&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///5,60205,&quot;風&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///6,60206,&quot;暴風&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///7,60207,&quot;雨&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///8,60208,&quot;暴雨&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;
        ///9,60209,&quot;雷&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&....
        /// </summary>
        public static string weatherJP {
            get {
                return ResourceManager.GetString("weatherJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [0x6][0x0],1 [0x3][0x20],2 [0x6][0x4],3 [0x3][0x21],4 [0x6][0x8],5 [0x3][0x22],6 [0x6][0xc],7 [0x3][0x23],8 [0x6][0x10],9 [0x3][0x24],10 [0x6][0x14],11 [0x3][0x25],12 [0x6][0x18],13 [0x3][0x26],14 [0x6][0x1c],15 [0x3][0x27]
        ///0,2,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        ///1,7,5,7,15,4,10,3,10,2,15,1,30,2,15,0,0
        ///2,7,5,7,15,4,10,3,10,2,15,1,30,2,15,0,0
        ///3,9,5,7,15,4,10,3,10,2,15,1,30,2,15,0,0
        ///4,9,5,7,15,4,10,3,10,2,15,1,30,2,15,0,0
        ///5,4,5,10,5,9,15,4,5,3,10,2,30,1,30,0,0
        ///6,4,5,8,5,7,15,4,5,3,10,2,30,1,30,0,0
        ///7,1,40, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string weatherrate_exh {
            get {
                return ResourceManager.GetString("weatherrate_exh", resourceCulture);
            }
        }
    }
}
